/* Natural Science — las 4 fichas del cole en datos (fuente: fotos en ../NaturalScience/, NS-D1). BILINGÜE como las fichas (NS-D3):
   lo que entra en el examen va en INGLÉS (def, q, options, items, labels) con su castellano al lado (def_es, es, oes, ies, bes…);
   las instrucciones, ánimos, chistes y curiosidades van en castellano. Nada se inventa: definiciones y listas son las de las fichas.
   keys = grupos de palabras clave (en inglés) que tiene que contener la definición escrita; min = grupos necesarios. */
window.NS = (function () {
  const worlds = {
    living: { id: 'living', series: 'mha', title: 'Living and non-living things', title_es: 'Seres vivos y seres inertes', sub: 'Funciones vitales, natural y artificial', hero: 'deku', heroName: 'Deku', heroImg: '../shared/img/st_deku.webp', bg: '../ciencias/assets/img/bg_mha.webp', music: 'music_mha', boss: { id: 'gentle', name: 'Gentle Criminal', img: '../ciencias/assets/img/boss_gentle.webp', hp: 8, intro: '¡Gentle Criminal quiere mezclar los seres vivos con los inertes!' }, win: '../ciencias/assets/img/win_mha.webp', intro: 'w_living', badge: '🌱' },
    cells: { id: 'cells', series: 'haikyuu', title: 'From a cell to an organism', title_es: 'De la célula al organismo', sub: 'Células, unicelulares y pluricelulares', hero: 'hinata', heroName: 'Hinata', heroImg: '../tablas/assets/img/ch_hinata.webp', bg: '../tablas/assets/img/bg_haikyuu.webp', music: 'music_haikyuu', boss: { id: 'kuroo', name: 'Kuroo (Nekoma)', img: '../tablas/assets/img/boss_kuroo.webp', hp: 8, intro: '¡Kuroo te reta: un jugador es una célula y el equipo es el organismo!' }, win: '../tablas/assets/img/win_haikyuu.webp', intro: 'w_cells', badge: '🔬' },
    cellparts: { id: 'cellparts', series: 'demonslayer', title: 'Animal cell and plant cell', title_es: 'Célula animal y célula vegetal', sub: 'Las partes de la célula', hero: 'nezuko', heroName: 'Nezuko', heroImg: '../tablas/assets/img/ch_nezuko.webp', bg: '../tablas/assets/img/bg_demonslayer.webp', music: 'music_demonslayer', boss: { id: 'oni', name: 'El oni de la montaña', img: '../tablas/assets/img/boss_demon.webp', hp: 8, intro: '¡El oni quiere robar el núcleo de todas las células!' }, win: '../tablas/assets/img/win_demonslayer.webp', intro: 'w_cellparts', badge: '🧫' },
    kingdoms: { id: 'kingdoms', series: 'onepiece', title: 'The five kingdoms', title_es: 'Los cinco reinos', sub: 'Plantas, animales, hongos, moneras y protistas', hero: 'luffy', heroName: 'Luffy', heroImg: '../tablas/assets/img/ch_luffy.webp', bg: '../tablas/assets/img/bg_onepiece.webp', music: 'music_onepiece', boss: { id: 'buggy', name: 'Buggy el Payaso', img: '../tablas/assets/img/boss_buggy.webp', hp: 8, intro: '¡Buggy quiere mandar en los cinco reinos!' }, win: '../tablas/assets/img/win_onepiece.webp', intro: 'w_kingdoms', badge: '👑' },
  };
  const WORLD_ORDER = ['living', 'cells', 'cellparts', 'kingdoms'];

  // ---------- conceptos: lo que hay que saber definir en inglés (modo ESCRIBIR, lección de 3 tiempos, unir) ----------
  const concepts = [
    // Living and non-living things
    { id: 'living_things', world: 'living', name: 'living things', name_es: 'los seres vivos', q: 'What are living things?', es: '¿Qué son los seres vivos?', def: 'Living things are born, grow, reproduce and die.', def_es: 'Los seres vivos nacen, crecen, se reproducen y mueren.', short: 'They are born, grow, reproduce and die', short_es: 'Nacen, crecen, se reproducen y mueren', keys: [['born'], ['grow'], ['reproduce', 'babies'], ['die']], min: 3 },
    { id: 'vital_functions', world: 'living', name: 'the three vital functions', name_es: 'las tres funciones vitales', q: 'What are the three vital functions of living things?', es: '¿Cuáles son las tres funciones vitales de los seres vivos?', def: 'Living things perform three vital functions: nutrition, reproduction and interaction.', def_es: 'Los seres vivos realizan tres funciones vitales: nutrición, reproducción e interacción (relación).', short: 'Nutrition, reproduction and interaction', short_es: 'Nutrición, reproducción e interacción', keys: [['nutrition'], ['reproduction'], ['interaction']] },
    { id: 'nutrition', world: 'living', name: 'nutrition', name_es: 'la nutrición', q: 'What is nutrition?', es: '¿Qué es la nutrición?', def: 'Nutrition is when living things get energy from food.', def_es: 'La nutrición es cuando los seres vivos obtienen energía de los alimentos.', short: 'They get energy from food', short_es: 'Obtienen energía de los alimentos', keys: [['food', 'eat', 'eating'], ['energy']], min: 1 },
    { id: 'reproduction', world: 'living', name: 'reproduction', name_es: 'la reproducción', q: 'What is reproduction?', es: '¿Qué es la reproducción?', def: 'Reproduction is when living things have babies.', def_es: 'La reproducción es cuando los seres vivos tienen crías.', short: 'They have babies', short_es: 'Tienen crías', keys: [['babies', 'baby', 'young', 'offspring', 'children', 'kids']] },
    { id: 'interaction', world: 'living', name: 'interaction', name_es: 'la interacción', q: 'What is interaction?', es: '¿Qué es la interacción?', def: 'Interaction is when living things relate to the environment.', def_es: 'La interacción es cuando los seres vivos se relacionan con el medio que los rodea.', short: 'They relate to the environment', short_es: 'Se relacionan con el medio', keys: [['relate', 'react', 'respond', 'interact', 'relationship', 'connect'], ['environment', 'surroundings', 'around them', 'world']], min: 1 },
    { id: 'living_groups', world: 'living', name: 'the two groups of living things', name_es: 'los dos grupos de seres vivos', q: 'What two groups of living things are there?', es: '¿Qué dos grupos de seres vivos hay?', def: 'There are two groups of living things: animals and plants.', def_es: 'Hay dos grupos de seres vivos: los animales y las plantas.', short: 'Animals and plants', short_es: 'Animales y plantas', keys: [['animals', 'animal'], ['plants', 'plant']] },
    { id: 'nonliving_groups', world: 'living', name: 'the two groups of non-living things', name_es: 'los dos grupos de seres inertes', q: 'What two groups of non-living things are there?', es: '¿Qué dos grupos de seres inertes hay?', def: 'There are two groups of non-living things: natural and artificial.', def_es: 'Hay dos grupos de seres inertes: los naturales y los artificiales.', short: 'Natural and artificial', short_es: 'Naturales y artificiales', keys: [['natural'], ['artificial']] },
    { id: 'natural_things', world: 'living', name: 'natural non-living things', name_es: 'los seres inertes naturales', q: 'What are natural non-living things? Give examples.', es: '¿Qué son los seres inertes naturales? Pon ejemplos.', def: 'Natural non-living things are not made by people, like the sea, the sun or a volcano.', def_es: 'Los seres inertes naturales no los hacen las personas, como el mar, el sol o un volcán.', short: 'Not made by people: the sea, the sun, a volcano', short_es: 'No los hacen las personas: el mar, el sol, un volcán', keys: [['not made', 'nature', 'naturally', 'nobody made', 'no one made', 'not built'], ['sea', 'sun', 'volcano', 'wave', 'water', 'rock', 'rocks', 'mountain', 'cloud', 'clouds', 'river', 'moon']], min: 1 },
    { id: 'artificial_things', world: 'living', name: 'artificial non-living things', name_es: 'los seres inertes artificiales', q: 'What are artificial non-living things? Give examples.', es: '¿Qué son los seres inertes artificiales? Pon ejemplos.', def: 'Artificial non-living things are made by people, like a bicycle, a balloon or shoes.', def_es: 'Los seres inertes artificiales los hacen las personas, como una bicicleta, un globo o unas zapatillas.', short: 'Made by people: a bicycle, a balloon, shoes', short_es: 'Los hacen las personas: una bicicleta, un globo, unas zapatillas', keys: [['made by people', 'people make', 'people made', 'humans', 'man made', 'made by humans', 'we make', 'built', 'made by'], ['bicycle', 'bike', 'balloon', 'shoes', 'shoe', 'car', 'toy', 'toys', 'book', 'table', 'chair', 'house', 'phone']], min: 1 },
    // From a cell to an organism
    { id: 'cell', world: 'cells', name: 'a cell', name_es: 'una célula', q: 'What is a cell?', es: '¿Qué es una célula?', def: 'A cell is the smallest living unit.', def_es: 'Una célula es la unidad más pequeña de un ser vivo.', short: 'The smallest living unit', short_es: 'La unidad más pequeña de un ser vivo', keys: [['smallest', 'small'], ['living'], ['unit', 'part', 'piece']], min: 2 },
    { id: 'cell_types', world: 'cells', name: 'the two types of cells', name_es: 'los dos tipos de células', q: 'What two types of cells are there?', es: '¿Qué dos tipos de células hay?', def: 'There are two types of cells: plant cells and animal cells.', def_es: 'Hay dos tipos de células: las células vegetales y las células animales.', short: 'Plant cells and animal cells', short_es: 'Células vegetales y células animales', keys: [['plant'], ['animal']] },
    { id: 'microscope', world: 'cells', name: 'the microscope', name_es: 'el microscopio', q: 'How can we see individual cells?', es: '¿Cómo podemos ver las células una a una?', def: 'We need a microscope to see individual cells.', def_es: 'Necesitamos un microscopio para ver las células.', short: 'With a microscope', short_es: 'Con un microscopio', keys: [['microscope']] },
    { id: 'unicellular', world: 'cells', name: 'unicellular organisms', name_es: 'los organismos unicelulares', q: 'What are unicellular organisms? Give an example.', es: '¿Qué son los organismos unicelulares? Pon un ejemplo.', def: 'Unicellular organisms have only one cell, like bacteria and algae.', def_es: 'Los organismos unicelulares tienen una sola célula, como las bacterias y las algas.', short: 'Only ONE cell (bacteria, algae)', short_es: 'Una SOLA célula (bacterias, algas)', keys: [['one cell', '1 cell', 'single cell', 'only one', 'just one']] },
    { id: 'multicellular', world: 'cells', name: 'multicellular organisms', name_es: 'los organismos pluricelulares', q: 'What are multicellular organisms? Give an example.', es: '¿Qué son los organismos pluricelulares? Pon un ejemplo.', def: 'Multicellular organisms have many cells, like a plant, an animal or a person.', def_es: 'Los organismos pluricelulares tienen muchas células, como una planta, un animal o una persona.', short: 'MANY cells (plant, animal, person)', short_es: 'MUCHAS células (planta, animal, persona)', keys: [['many cells', 'lots of cells', 'a lot of cells', 'many', 'lots', 'more than one']] },
    { id: 'organised', world: 'cells', name: 'how cells are organised', name_es: 'cómo se organizan las células', q: 'How are cells organised?', es: '¿Cómo se organizan las células?', def: 'Cells form tissues, tissues form organs, organs form organ systems and organ systems form an organism.', def_es: 'Las células forman tejidos, los tejidos forman órganos, los órganos forman sistemas de órganos y los sistemas forman un organismo.', short: 'cell → tissue → organ → organ system → organism', short_es: 'célula → tejido → órgano → sistema de órganos → organismo', keys: [['tissue'], ['organ'], ['system'], ['organism']], min: 3 },
    { id: 'plant_example', world: 'cells', name: 'the plant example', name_es: 'el ejemplo de la planta', q: 'Give the example of how a plant is organised.', es: 'Di el ejemplo de cómo se organiza una planta.', def: 'In a plant: cell, tissue, leaf, plant organ system and plant.', def_es: 'En una planta: célula, tejido, hoja, sistema de órganos de la planta y planta.', short: 'cell → tissue → leaf → plant organ system → plant', short_es: 'célula → tejido → hoja → sistema de órganos → planta', keys: [['tissue'], ['leaf'], ['plant']], min: 2 },
    { id: 'animal_example', world: 'cells', name: 'the animal example', name_es: 'el ejemplo del animal', q: 'Give the example of how an animal is organised.', es: 'Di el ejemplo de cómo se organiza un animal.', def: 'In an animal: cell, tissue, heart, circulatory system and animal.', def_es: 'En un animal: célula, tejido, corazón, sistema circulatorio y animal.', short: 'cell → tissue → heart → circulatory system → animal', short_es: 'célula → tejido → corazón → sistema circulatorio → animal', keys: [['tissue'], ['heart'], ['circulatory'], ['animal']], min: 3 },
    // Animal cell and plant cell
    { id: 'animal_cell_parts', world: 'cellparts', name: 'the parts of an animal cell', name_es: 'las partes de la célula animal', q: 'What parts does an animal cell have?', es: '¿Qué partes tiene una célula animal?', def: 'An animal cell has a cell membrane, a nucleus and small vacuoles.', def_es: 'Una célula animal tiene membrana celular, núcleo y vacuolas pequeñas.', short: 'Cell membrane, nucleus and small vacuoles', short_es: 'Membrana celular, núcleo y vacuolas pequeñas', keys: [['membrane'], ['nucleus'], ['vacuole', 'vacuoles']], min: 2 },
    { id: 'plant_cell_parts', world: 'cellparts', name: 'the parts of a plant cell', name_es: 'las partes de la célula vegetal', q: 'What parts does a plant cell have?', es: '¿Qué partes tiene una célula vegetal?', def: 'A plant cell has a cell wall, chloroplasts, a cell membrane, a large vacuole and a nucleus.', def_es: 'Una célula vegetal tiene pared celular, cloroplastos, membrana celular, una vacuola grande y núcleo.', short: 'Cell wall, chloroplasts, cell membrane, large vacuole and nucleus', short_es: 'Pared celular, cloroplastos, membrana, vacuola grande y núcleo', keys: [['wall'], ['chloroplast', 'chloroplasts'], ['membrane'], ['vacuole'], ['nucleus']], min: 4 },
    { id: 'cell_difference', world: 'cellparts', name: 'the difference between a plant cell and an animal cell', name_es: 'la diferencia entre la célula vegetal y la animal', q: 'What is the difference between a plant cell and an animal cell?', es: '¿En qué se diferencian una célula vegetal y una animal?', def: 'Only the plant cell has a cell wall and chloroplasts. The plant cell has a large vacuole and the animal cell has small vacuoles.', def_es: 'Solo la célula vegetal tiene pared celular y cloroplastos. La vegetal tiene una vacuola grande y la animal, vacuolas pequeñas.', short: 'Only the plant cell has a cell wall and chloroplasts; its vacuole is large, the animal cell has small ones', short_es: 'Solo la vegetal tiene pared y cloroplastos; su vacuola es grande y la animal las tiene pequeñas', keys: [['wall'], ['chloroplast', 'chloroplasts'], ['large', 'big', 'small']], min: 2 },
    // The five kingdoms
    { id: 'five_kingdoms', world: 'kingdoms', name: 'the five kingdoms', name_es: 'los cinco reinos', q: 'What are the five kingdoms?', es: '¿Cuáles son los cinco reinos?', def: 'The five kingdoms are plants, animals, fungi, monera and protists.', def_es: 'Los cinco reinos son: plantas, animales, hongos, moneras y protistas.', short: 'Plants, animals, fungi, monera and protists', short_es: 'Plantas, animales, hongos, moneras y protistas', keys: [['plants', 'plant'], ['animals', 'animal'], ['fungi', 'fungus'], ['monera'], ['protists', 'protist']], min: 4 },
    { id: 'plants_k', world: 'kingdoms', name: 'the plant kingdom', name_es: 'el reino de las plantas', q: 'What are plants like?', es: '¿Cómo son las plantas?', def: 'Plants are multicellular and make their own food.', def_es: 'Las plantas son pluricelulares y fabrican su propio alimento.', short: 'Multicellular · make their own food', short_es: 'Pluricelulares · fabrican su propio alimento', keys: [['multicellular', 'many cells'], ['own food', 'their food', 'make food', 'their own', 'make their']] },
    { id: 'animals_k', world: 'kingdoms', name: 'the animal kingdom', name_es: 'el reino de los animales', q: 'What are animals like?', es: '¿Cómo son los animales?', def: 'Animals are multicellular. They feed on other living things and lay eggs or give birth.', def_es: 'Los animales son pluricelulares. Se alimentan de otros seres vivos y ponen huevos o dan a luz a crías.', short: 'Multicellular · feed on other living things · lay eggs or give birth', short_es: 'Pluricelulares · se alimentan de otros seres vivos · ponen huevos o dan a luz', keys: [['multicellular', 'many cells'], ['feed', 'eat', 'other living'], ['eggs', 'birth', 'babies']], min: 2 },
    { id: 'fungi_k', world: 'kingdoms', name: 'the fungi kingdom', name_es: 'el reino de los hongos', q: 'What are fungi like?', es: '¿Cómo son los hongos?', def: 'Fungi can be multicellular or unicellular. They get nutrients from dead plants and animals. They cannot move.', def_es: 'Los hongos pueden ser pluricelulares o unicelulares. Obtienen nutrientes de plantas y animales muertos. No pueden moverse.', short: 'Multicellular or unicellular · nutrients from dead plants and animals · cannot move', short_es: 'Pluri o unicelulares · nutrientes de plantas y animales muertos · no se mueven', keys: [['dead'], ['cannot move', 'can not move', 'cant move', 'not move', 'dont move', 'do not move', 'never move'], ['multicellular', 'unicellular', 'one cell', 'many cells']], min: 2 },
    { id: 'monera_k', world: 'kingdoms', name: 'the monera kingdom', name_es: 'el reino de las moneras', q: 'What are monera like?', es: '¿Cómo son las moneras?', def: 'Monera are unicellular. Some feed on dead plants and animals.', def_es: 'Las moneras son unicelulares. Algunas se alimentan de plantas y animales muertos.', short: 'Unicellular · some feed on dead plants and animals', short_es: 'Unicelulares · algunas se alimentan de plantas y animales muertos', keys: [['unicellular', 'one cell', 'single cell'], ['dead']], min: 1 },
    { id: 'protists_k', world: 'kingdoms', name: 'the protist kingdom', name_es: 'el reino de los protistas', q: 'What are protists like?', es: '¿Cómo son los protistas?', def: 'Protists are usually unicellular. Most live in or near water.', def_es: 'Los protistas son generalmente unicelulares. La mayoría viven en el agua o cerca del agua.', short: 'Usually unicellular · most live in or near water', short_es: 'Generalmente unicelulares · la mayoría viven en el agua o cerca', keys: [['unicellular', 'one cell', 'single cell'], ['water']], min: 1 },
  ];

  // ---------- listas: elegir todos los que son (modo TEST); los items se traducen con el vocabulario ----------
  const lists = [
    { id: 'living_list', world: 'living', q: 'Which of these are living things?', es: '¿Cuáles de estos son seres vivos?', items: ['Flamingo', 'Fox', 'Seal', 'Tree', 'Flower'], distractors: ['Sun', 'Volcano', 'Bicycle', 'Balloon'] },
    { id: 'nonliving_list', world: 'living', q: 'Which of these are non-living things?', es: '¿Cuáles de estos son seres inertes?', items: ['Sun', 'Wave', 'Volcano', 'Bicycle', 'Shoes'], distractors: ['Fox', 'Seal', 'Flower', 'Tree'] },
    { id: 'vital_list', world: 'living', q: 'Which are the three vital functions?', es: '¿Cuáles son las tres funciones vitales?', items: ['Nutrition', 'Reproduction', 'Interaction'], distractors: ['Flying', 'Sleeping', 'Running', 'Talking'] },
    { id: 'natural_list', world: 'living', q: 'Which of these are NATURAL non-living things?', es: '¿Cuáles de estos son seres inertes NATURALES?', items: ['Sun', 'Sea', 'Volcano', 'Rock'], distractors: ['Bicycle', 'Balloon', 'Shoes', 'Flower'] },
    { id: 'artificial_list', world: 'living', q: 'Which of these are ARTIFICIAL non-living things?', es: '¿Cuáles de estos son seres inertes ARTIFICIALES?', items: ['Bicycle', 'Balloon', 'Shoes', 'Car'], distractors: ['Sun', 'Volcano', 'Wave', 'Fox'] },
    { id: 'unicellular_list', world: 'cells', q: 'Which of these are unicellular organisms?', es: '¿Cuáles de estos son organismos unicelulares?', items: ['Bacteria', 'Algae', 'Amoeba'], distractors: ['Dog', 'Tree', 'Person', 'Rabbit'] },
    { id: 'multicellular_list', world: 'cells', q: 'Which of these are multicellular organisms?', es: '¿Cuáles de estos son organismos pluricelulares?', items: ['Plant', 'Animal', 'Person', 'Dog', 'Tree'], distractors: ['Bacteria', 'Amoeba'] },
    { id: 'levels_list', world: 'cells', q: 'Which are the levels of organisation of cells?', es: '¿Cuáles son los niveles de organización de las células?', items: ['Cell', 'Tissue', 'Organ', 'Organ system', 'Organism'], distractors: ['Microscope', 'Kingdom', 'Food', 'Volcano'] },
    { id: 'plant_cell_list', world: 'cellparts', q: 'Which parts does a PLANT cell have?', es: '¿Qué partes tiene una célula VEGETAL?', items: ['Cell wall', 'Chloroplast', 'Cell membrane', 'Large vacuole', 'Nucleus'], distractors: ['Small vacuole', 'Heart', 'Leaf', 'Bone'] },
    { id: 'animal_cell_list', world: 'cellparts', q: 'Which parts does an ANIMAL cell have?', es: '¿Qué partes tiene una célula ANIMAL?', items: ['Cell membrane', 'Nucleus', 'Small vacuole'], distractors: ['Cell wall', 'Chloroplast', 'Large vacuole', 'Leaf'] },
    { id: 'only_plant_list', world: 'cellparts', q: 'Which parts has ONLY the plant cell (not the animal cell)?', es: '¿Qué partes tiene SOLO la célula vegetal (y no la animal)?', items: ['Cell wall', 'Chloroplast'], distractors: ['Nucleus', 'Cell membrane', 'Small vacuole'] },
    { id: 'kingdoms_list', world: 'kingdoms', q: 'Which are the five kingdoms?', es: '¿Cuáles son los cinco reinos?', items: ['Plants', 'Animals', 'Fungi', 'Monera', 'Protists'], distractors: ['Insects', 'Fish', 'Birds', 'Rocks'] },
    { id: 'multicell_kingdoms', world: 'kingdoms', q: 'Which kingdoms are ALWAYS multicellular?', es: '¿Qué reinos son SIEMPRE pluricelulares?', items: ['Plants', 'Animals'], distractors: ['Monera', 'Protists', 'Fungi'] },
    { id: 'dead_feeders', world: 'kingdoms', q: 'Which kingdoms can feed on dead plants and animals?', es: '¿Qué reinos pueden alimentarse de plantas y animales muertos?', items: ['Fungi', 'Monera'], distractors: ['Plants', 'Animals', 'Protists'] },
  ];

  // ---------- clasificar: cada cosa a su cajón (modo UNIR); bes = cajones en castellano, ies = items en castellano (mismo orden) ----------
  const sorts = [
    { id: 'living_nonliving', world: 'living', q: 'Living or non-living?', es: '¿Ser vivo o ser inerte?', bins: ['Living things', 'Non-living things'], bes: ['Seres vivos', 'Seres inertes'], items: [['Flamingo', 0], ['Fox', 0], ['Seal', 0], ['Tree', 0], ['Flower', 0], ['Sun', 1], ['Volcano', 1], ['Wave', 1], ['Bicycle', 1], ['Balloon', 1]], ies: ['flamenco', 'zorro', 'foca', 'árbol', 'flor', 'sol', 'volcán', 'ola', 'bicicleta', 'globo'] },
    { id: 'natural_artificial', world: 'living', q: 'Natural or artificial?', es: '¿Natural o artificial?', bins: ['Natural', 'Artificial'], bes: ['Natural', 'Artificial'], items: [['The sun', 0], ['A wave', 0], ['A volcano', 0], ['A rock', 0], ['A bicycle', 1], ['A balloon', 1], ['Shoes', 1], ['A car', 1]], ies: ['el sol', 'una ola', 'un volcán', 'una roca', 'una bicicleta', 'un globo', 'unas zapatillas', 'un coche'] },
    { id: 'vital_sort', world: 'living', q: 'Which vital function is it?', es: '¿Qué función vital es?', bins: ['Nutrition', 'Reproduction', 'Interaction'], bes: ['Nutrición', 'Reproducción', 'Interacción'], items: [['A dog eating from its bowl', 0], ['A cow eating grass', 0], ['A cat with her kittens', 1], ['A bird laying eggs', 1], ['A dog chasing a butterfly', 2], ['A plant growing towards the light', 2]], ies: ['un perro comiendo de su cuenco', 'una vaca comiendo hierba', 'una gata con sus gatitos', 'un pájaro poniendo huevos', 'un perro persiguiendo una mariposa', 'una planta creciendo hacia la luz'] },
    { id: 'uni_multi', world: 'cells', q: 'Unicellular or multicellular?', es: '¿Unicelular o pluricelular?', bins: ['Unicellular', 'Multicellular'], bes: ['Unicelular', 'Pluricelular'], items: [['Bacteria', 0], ['Algae', 0], ['Amoeba', 0], ['A plant', 1], ['A dog', 1], ['A person', 1], ['A tree', 1]], ies: ['bacterias', 'algas', 'ameba', 'una planta', 'un perro', 'una persona', 'un árbol'] },
    { id: 'levels_sort', world: 'cells', q: 'Which level of organisation is it?', es: '¿Qué nivel de organización es?', bins: ['Organ', 'Organ system', 'Organism'], bes: ['Órgano', 'Sistema de órganos', 'Organismo'], items: [['Heart', 0], ['Leaf', 0], ['Circulatory system', 1], ['Plant organ system', 1], ['Dog', 2], ['Plant', 2]], ies: ['corazón', 'hoja', 'sistema circulatorio', 'sistema de órganos de la planta', 'perro', 'planta'] },
    { id: 'cell_parts_sort', world: 'cellparts', q: 'Plant cell, animal cell or both?', es: '¿Célula vegetal, animal o las dos?', bins: ['Only plant cell', 'Only animal cell', 'Both'], bes: ['Solo la vegetal', 'Solo la animal', 'Las dos'], items: [['Cell wall', 0], ['Chloroplast', 0], ['Large vacuole', 0], ['Small vacuole', 1], ['Nucleus', 2], ['Cell membrane', 2]], ies: ['pared celular', 'cloroplasto', 'vacuola grande', 'vacuola pequeña', 'núcleo', 'membrana celular'] },
    { id: 'kingdoms_sort', world: 'kingdoms', q: 'Which kingdom?', es: '¿Qué reino?', bins: ['Plants', 'Animals', 'Fungi', 'Monera', 'Protists'], bes: ['Plantas', 'Animales', 'Hongos', 'Moneras', 'Protistas'], items: [['Sunflower', 0], ['Tree', 0], ['Rabbit', 1], ['Bird', 1], ['Mushroom', 2], ['Bacteria', 3], ['Amoeba', 4], ['Algae', 4]], ies: ['girasol', 'árbol', 'conejo', 'pájaro', 'seta', 'bacterias', 'ameba', 'algas'] },
    { id: 'kingdom_facts_sort', world: 'kingdoms', q: 'Which kingdom is it?', es: '¿De qué reino hablo?', bins: ['Plants', 'Animals', 'Fungi'], bes: ['Plantas', 'Animales', 'Hongos'], items: [['They make their own food', 0], ['They lay eggs or give birth', 1], ['They cannot move and eat dead plants', 2], ['They feed on other living things', 1], ['Mushrooms', 2], ['Trees and flowers', 0]], ies: ['fabrican su propio alimento', 'ponen huevos o dan a luz a crías', 'no se mueven y comen plantas muertas', 'se alimentan de otros seres vivos', 'las setas', 'los árboles y las flores'] },
  ];

  // ---------- preguntas sueltas: elegir (choice), verdadero/falso (tf), reto de pensar (reto). es = pregunta en castellano, oes = opciones, wes = explicación ----------
  const questions = [
    // Living and non-living things
    { type: 'choice', world: 'living', q: 'Living things are born, grow, reproduce and…', es: 'Los seres vivos nacen, crecen, se reproducen y…', options: ['fly', 'die', 'sleep', 'swim'], oes: ['vuelan', 'mueren', 'duermen', 'nadan'], a: 1 },
    { type: 'choice', world: 'living', q: 'How many vital functions do living things perform?', es: '¿Cuántas funciones vitales realizan los seres vivos?', options: ['Two', 'Three', 'Four', 'Five'], oes: ['dos', 'tres', 'cuatro', 'cinco'], a: 1 },
    { type: 'choice', world: 'living', q: 'Getting energy from food is…', es: 'Obtener energía de los alimentos es…', options: ['nutrition', 'reproduction', 'interaction'], oes: ['la nutrición', 'la reproducción', 'la interacción'], a: 0 },
    { type: 'choice', world: 'living', q: 'Having babies is…', es: 'Tener crías es…', options: ['nutrition', 'reproduction', 'interaction'], oes: ['la nutrición', 'la reproducción', 'la interacción'], a: 1 },
    { type: 'choice', world: 'living', q: 'Relating to the environment is…', es: 'Relacionarse con el medio es…', options: ['nutrition', 'reproduction', 'interaction'], oes: ['la nutrición', 'la reproducción', 'la interacción'], a: 2 },
    { type: 'choice', world: 'living', q: 'Which of these is a living thing?', es: '¿Cuál de estos es un ser vivo?', options: ['A volcano', 'A flower', 'A balloon', 'The sun'], oes: ['un volcán', 'una flor', 'un globo', 'el sol'], a: 1, why: 'A flower is a plant: it is born, grows, reproduces and dies.', wes: 'Una flor es una planta: nace, crece, se reproduce y muere.' },
    { type: 'choice', world: 'living', q: 'Which of these is a NATURAL non-living thing?', es: '¿Cuál de estos es un ser inerte NATURAL?', options: ['A bicycle', 'A pair of shoes', 'A volcano', 'A fox'], oes: ['una bicicleta', 'unas zapatillas', 'un volcán', 'un zorro'], a: 2, why: 'A volcano is not alive and nobody made it: natural.', wes: 'Un volcán no está vivo y nadie lo ha hecho: natural.' },
    { type: 'choice', world: 'living', q: 'Which of these is an ARTIFICIAL non-living thing?', es: '¿Cuál de estos es un ser inerte ARTIFICIAL?', options: ['The sea', 'A balloon', 'A seal', 'The sun'], oes: ['el mar', 'un globo', 'una foca', 'el sol'], a: 1, why: 'A balloon is made by people: artificial.', wes: 'Un globo lo hacen las personas: artificial.' },
    { type: 'choice', world: 'living', q: 'The two groups of living things are…', es: 'Los dos grupos de seres vivos son…', options: ['animals and plants', 'natural and artificial', 'big and small'], oes: ['animales y plantas', 'naturales y artificiales', 'grandes y pequeños'], a: 0 },
    { type: 'choice', world: 'living', q: 'The two groups of non-living things are…', es: 'Los dos grupos de seres inertes son…', options: ['animals and plants', 'natural and artificial', 'hot and cold'], oes: ['animales y plantas', 'naturales y artificiales', 'calientes y fríos'], a: 1 },
    { type: 'tf', world: 'living', s: 'Living things are born, grow, reproduce and die.', es: 'Los seres vivos nacen, crecen, se reproducen y mueren.', a: true },
    { type: 'tf', world: 'living', s: 'A bicycle is a living thing.', es: 'Una bicicleta es un ser vivo.', a: false, why: 'A bicycle is an artificial non-living thing: people make it.', wes: 'Una bicicleta es un ser inerte artificial: la hacen las personas.' },
    { type: 'tf', world: 'living', s: 'The sun is a natural non-living thing.', es: 'El sol es un ser inerte natural.', a: true },
    { type: 'tf', world: 'living', s: 'Plants are not living things.', es: 'Las plantas no son seres vivos.', a: false, why: 'Plants are living things: they are born, grow, reproduce and die.', wes: 'Las plantas son seres vivos: nacen, crecen, se reproducen y mueren.' },
    { type: 'tf', world: 'living', s: 'Interaction is when living things have babies.', es: 'La interacción es cuando los seres vivos tienen crías.', a: false, why: 'Having babies is reproduction. Interaction is relating to the environment.', wes: 'Tener crías es la reproducción. La interacción es relacionarse con el medio.' },
    { type: 'tf', world: 'living', s: 'Nutrition is getting energy from food.', es: 'La nutrición es obtener energía de los alimentos.', a: true },
    { type: 'reto', world: 'living', q: 'A dog runs away when it hears a loud noise. Which vital function is that?', es: 'Un perro sale corriendo al oír un ruido fuerte. ¿Qué función vital es?', options: ['Nutrition', 'Reproduction', 'Interaction'], oes: ['nutrición', 'reproducción', 'interacción'], a: 2, why: 'It is relating to the environment: interaction.', wes: 'Se está relacionando con el medio: interacción.' },
    { type: 'reto', world: 'living', q: 'A robot moves, makes noise and needs batteries. Is it a living thing?', es: 'Un robot se mueve, hace ruido y necesita pilas. ¿Es un ser vivo?', options: ['No: people made it, it is artificial', 'Yes: it moves', 'Yes: it needs energy'], oes: ['No: lo hacen las personas, es artificial', 'Sí: se mueve', 'Sí: necesita energía'], a: 0, why: 'It was not born, it does not grow and it does not reproduce: it is an artificial non-living thing.', wes: 'No ha nacido, no crece y no se reproduce: es un ser inerte artificial.' },
    { type: 'reto', world: 'living', q: 'A seed becomes a tree. Which vital function do you see?', es: 'Una semilla se convierte en un árbol. ¿Qué función vital ves?', options: ['Interaction', 'Reproduction', 'Nutrition'], oes: ['interacción', 'reproducción', 'nutrición'], a: 1, why: 'The seed comes from a plant having babies: reproduction. The tree also grows.', wes: 'La semilla viene de una planta que tiene «crías»: reproducción. Además, el árbol crece.' },
    { type: 'reto', world: 'living', q: 'A sunflower turns to follow the sun. Which vital function is that?', es: 'Un girasol se gira para seguir al sol. ¿Qué función vital es?', options: ['Interaction', 'Reproduction', 'Nutrition'], oes: ['interacción', 'reproducción', 'nutrición'], a: 0 },
    { type: 'reto', world: 'living', q: 'A rock gets bigger when a child paints it. Is the rock growing like a living thing?', es: 'Una roca se hace más grande cuando un niño la pinta. ¿Está creciendo como un ser vivo?', options: ['No: it is not alive, it just has paint on it', 'Yes: it is bigger', 'Yes: rocks are plants'], oes: ['No: no está viva, solo tiene pintura encima', 'Sí: es más grande', 'Sí: las rocas son plantas'], a: 0 },
    { type: 'reto', world: 'living', q: 'Deku\'s trainers: natural or artificial?', es: 'Las zapatillas de Deku: ¿naturales o artificiales?', options: ['Artificial: people made them', 'Natural: they came from a tree', 'Living: they can run'], oes: ['Artificiales: las hicieron personas', 'Naturales: salieron de un árbol', 'Vivas: saben correr'], a: 0 },
    // From a cell to an organism
    { type: 'choice', world: 'cells', q: 'The smallest living unit is…', es: 'La unidad más pequeña de un ser vivo es…', options: ['a cell', 'an organ', 'a tissue', 'an organism'], oes: ['una célula', 'un órgano', 'un tejido', 'un organismo'], a: 0 },
    { type: 'choice', world: 'cells', q: 'To see individual cells we need…', es: 'Para ver las células una a una necesitamos…', options: ['a telescope', 'a microscope', 'glasses', 'a magnifying glass'], oes: ['un telescopio', 'un microscopio', 'gafas', 'una lupa'], a: 1 },
    { type: 'choice', world: 'cells', q: 'Unicellular organisms have…', es: 'Los organismos unicelulares tienen…', options: ['only one cell', 'many cells', 'no cells', 'two cells'], oes: ['una sola célula', 'muchas células', 'ninguna célula', 'dos células'], a: 0 },
    { type: 'choice', world: 'cells', q: 'Multicellular organisms have…', es: 'Los organismos pluricelulares tienen…', options: ['only one cell', 'many cells', 'no cells'], oes: ['una sola célula', 'muchas células', 'ninguna célula'], a: 1 },
    { type: 'choice', world: 'cells', q: 'Which of these is unicellular?', es: '¿Cuál de estos es unicelular?', options: ['A dog', 'A tree', 'Bacteria', 'A person'], oes: ['un perro', 'un árbol', 'las bacterias', 'una persona'], a: 2 },
    { type: 'choice', world: 'cells', q: 'Which of these is multicellular?', es: '¿Cuál de estos es pluricelular?', options: ['Bacteria', 'Algae', 'Amoeba', 'A plant'], oes: ['las bacterias', 'las algas', 'la ameba', 'una planta'], a: 3 },
    { type: 'choice', world: 'cells', q: 'Cells form…', es: 'Las células forman…', options: ['tissues', 'organs', 'organisms', 'kingdoms'], oes: ['tejidos', 'órganos', 'organismos', 'reinos'], a: 0 },
    { type: 'choice', world: 'cells', q: 'Tissues form…', es: 'Los tejidos forman…', options: ['cells', 'organs', 'organisms'], oes: ['células', 'órganos', 'organismos'], a: 1 },
    { type: 'choice', world: 'cells', q: 'Organs form…', es: 'Los órganos forman…', options: ['cells', 'tissues', 'organ systems'], oes: ['células', 'tejidos', 'sistemas de órganos'], a: 2 },
    { type: 'choice', world: 'cells', q: 'Organ systems form…', es: 'Los sistemas de órganos forman…', options: ['an organism', 'a cell', 'a tissue'], oes: ['un organismo', 'una célula', 'un tejido'], a: 0 },
    { type: 'choice', world: 'cells', q: 'In the animal example, the organ is…', es: 'En el ejemplo del animal, el órgano es…', options: ['the heart', 'the leaf', 'the dog', 'the cell'], oes: ['el corazón', 'la hoja', 'el perro', 'la célula'], a: 0 },
    { type: 'choice', world: 'cells', q: 'In the plant example, the organ is…', es: 'En el ejemplo de la planta, el órgano es…', options: ['the heart', 'the leaf', 'the circulatory system'], oes: ['el corazón', 'la hoja', 'el sistema circulatorio'], a: 1 },
    { type: 'choice', world: 'cells', q: 'In the animal example, the organ system is…', es: 'En el ejemplo del animal, el sistema de órganos es…', options: ['the heart', 'the leaf', 'the circulatory system', 'the tissue'], oes: ['el corazón', 'la hoja', 'el sistema circulatorio', 'el tejido'], a: 2 },
    { type: 'tf', world: 'cells', s: 'A cell is the smallest living unit.', es: 'Una célula es la unidad más pequeña de un ser vivo.', a: true },
    { type: 'tf', world: 'cells', s: 'We can see one cell with our eyes.', es: 'Podemos ver una célula a simple vista.', a: false, why: 'We need a microscope to see individual cells.', wes: 'Necesitamos un microscopio para ver las células.' },
    { type: 'tf', world: 'cells', s: 'A person is a unicellular organism.', es: 'Una persona es un organismo unicelular.', a: false, why: 'A person has many cells: multicellular.', wes: 'Una persona tiene muchas células: pluricelular.' },
    { type: 'tf', world: 'cells', s: 'Bacteria have only one cell.', es: 'Las bacterias tienen una sola célula.', a: true },
    { type: 'tf', world: 'cells', s: 'Organs form tissues.', es: 'Los órganos forman tejidos.', a: false, why: 'It is the other way round: tissues form organs.', wes: 'Es al revés: los tejidos forman órganos.' },
    { type: 'tf', world: 'cells', s: 'The heart is an organ.', es: 'El corazón es un órgano.', a: true },
    { type: 'tf', world: 'cells', s: 'A leaf is a plant organ.', es: 'Una hoja es un órgano de la planta.', a: true },
    { type: 'reto', world: 'cells', q: 'Hinata is one player. The whole team plays together. If a player is a cell, the team is…', es: 'Hinata es un jugador. Todo el equipo juega junto. Si un jugador es una célula, el equipo es…', options: ['an organism', 'a microscope', 'a kingdom'], oes: ['un organismo', 'un microscopio', 'un reino'], a: 0, why: 'Many cells working together form an organism, like many players form a team.', wes: 'Muchas células trabajando juntas forman un organismo, como muchos jugadores forman un equipo.' },
    { type: 'reto', world: 'cells', q: 'Put in order from smallest to biggest:', es: 'Ordena de más pequeño a más grande:', options: ['cell → tissue → organ → organ system → organism', 'organism → organ → cell → tissue', 'tissue → cell → organism → organ'], oes: ['célula → tejido → órgano → sistema → organismo', 'organismo → órgano → célula → tejido', 'tejido → célula → organismo → órgano'], a: 0 },
    { type: 'reto', world: 'cells', q: 'An amoeba is just one cell. What is the amoeba?', es: 'Una ameba es una sola célula. ¿Qué es la ameba?', options: ['A unicellular organism', 'A multicellular organism', 'An organ'], oes: ['un organismo unicelular', 'un organismo pluricelular', 'un órgano'], a: 0 },
    { type: 'reto', world: 'cells', q: 'Which is bigger, a tissue or an organ?', es: '¿Qué es más grande, un tejido o un órgano?', options: ['An organ: it is made of tissues', 'A tissue: it is made of organs', 'They are the same size'], oes: ['Un órgano: está hecho de tejidos', 'Un tejido: está hecho de órganos', 'Son del mismo tamaño'], a: 0 },
    { type: 'reto', world: 'cells', q: 'Why can\'t you see bacteria on your hands?', es: '¿Por qué no puedes ver las bacterias de tus manos?', options: ['Because they are so small you need a microscope', 'Because they are invisible magic', 'Because they only live in water'], oes: ['Porque son tan pequeñas que hace falta un microscopio', 'Porque son magia invisible', 'Porque solo viven en el agua'], a: 0 },
    { type: 'reto', world: 'cells', q: 'A circulatory system is made of…', es: 'Un sistema circulatorio está hecho de…', options: ['organs, like the heart', 'only one cell', 'kingdoms'], oes: ['órganos, como el corazón', 'una sola célula', 'reinos'], a: 0 },
    // Animal cell and plant cell
    { type: 'choice', world: 'cellparts', q: 'Which part has ONLY the plant cell?', es: '¿Qué parte tiene SOLO la célula vegetal?', options: ['Nucleus', 'Cell wall', 'Cell membrane', 'Small vacuole'], oes: ['núcleo', 'pared celular', 'membrana celular', 'vacuola pequeña'], a: 1 },
    { type: 'choice', world: 'cellparts', q: 'Which part is green and only in plant cells?', es: '¿Qué parte es verde y solo está en las células vegetales?', options: ['Nucleus', 'Chloroplast', 'Vacuole', 'Membrane'], oes: ['núcleo', 'cloroplasto', 'vacuola', 'membrana'], a: 1 },
    { type: 'choice', world: 'cellparts', q: 'The plant cell has a … vacuole.', es: 'La célula vegetal tiene una vacuola…', options: ['large', 'small', 'no'], oes: ['grande', 'pequeña', 'no tiene'], a: 0 },
    { type: 'choice', world: 'cellparts', q: 'The animal cell has … vacuoles.', es: 'La célula animal tiene vacuolas…', options: ['large', 'small', 'green'], oes: ['grandes', 'pequeñas', 'verdes'], a: 1 },
    { type: 'choice', world: 'cellparts', q: 'Which parts do BOTH cells have?', es: '¿Qué partes tienen LAS DOS células?', options: ['Cell wall and chloroplast', 'Nucleus and cell membrane', 'Chloroplast and large vacuole'], oes: ['pared celular y cloroplasto', 'núcleo y membrana celular', 'cloroplasto y vacuola grande'], a: 1 },
    { type: 'choice', world: 'cellparts', q: 'The outside layer of an animal cell is the…', es: 'La capa de fuera de una célula animal es la…', options: ['cell membrane', 'cell wall', 'nucleus', 'chloroplast'], oes: ['membrana celular', 'pared celular', 'núcleo', 'cloroplasto'], a: 0 },
    { type: 'choice', world: 'cellparts', q: 'The outside layer of a PLANT cell is the…', es: 'La capa de fuera de una célula VEGETAL es la…', options: ['cell membrane', 'cell wall', 'nucleus', 'vacuole'], oes: ['membrana celular', 'pared celular', 'núcleo', 'vacuola'], a: 1 },
    { type: 'tf', world: 'cellparts', s: 'Animal cells have a cell wall.', es: 'Las células animales tienen pared celular.', a: false, why: 'Only plant cells have a cell wall.', wes: 'Solo las células vegetales tienen pared celular.' },
    { type: 'tf', world: 'cellparts', s: 'Plant cells have chloroplasts.', es: 'Las células vegetales tienen cloroplastos.', a: true },
    { type: 'tf', world: 'cellparts', s: 'Both plant and animal cells have a nucleus.', es: 'Las células vegetales y las animales tienen núcleo.', a: true },
    { type: 'tf', world: 'cellparts', s: 'The animal cell has a large vacuole.', es: 'La célula animal tiene una vacuola grande.', a: false, why: 'The animal cell has small vacuoles; the large vacuole is in the plant cell.', wes: 'La célula animal tiene vacuolas pequeñas; la vacuola grande está en la vegetal.' },
    { type: 'tf', world: 'cellparts', s: 'Both cells have a cell membrane.', es: 'Las dos células tienen membrana celular.', a: true },
    { type: 'tf', world: 'cellparts', s: 'Animal cells have chloroplasts.', es: 'Las células animales tienen cloroplastos.', a: false, why: 'Chloroplasts are only in plant cells.', wes: 'Los cloroplastos solo están en las células vegetales.' },
    { type: 'reto', world: 'cellparts', q: 'You see a cell with a cell wall and green chloroplasts. What is it?', es: 'Ves una célula con pared celular y cloroplastos verdes. ¿Qué es?', options: ['A plant cell', 'An animal cell'], oes: ['una célula vegetal', 'una célula animal'], a: 0 },
    { type: 'reto', world: 'cellparts', q: 'You see a cell with a nucleus, a membrane and small vacuoles, and NO wall. What is it?', es: 'Ves una célula con núcleo, membrana y vacuolas pequeñas, y SIN pared. ¿Qué es?', options: ['An animal cell', 'A plant cell'], oes: ['una célula animal', 'una célula vegetal'], a: 0 },
    { type: 'reto', world: 'cellparts', q: 'Nezuko\'s bamboo is hard on the outside, like a plant. Which cell part is hard and outside?', es: 'El bambú de Nezuko es duro por fuera, como una planta. ¿Qué parte de la célula es dura y está fuera?', options: ['The cell wall', 'The nucleus', 'The vacuole'], oes: ['la pared celular', 'el núcleo', 'la vacuola'], a: 0 },
    { type: 'reto', world: 'cellparts', q: 'How many parts do we label in the plant cell?', es: '¿Cuántas partes ponemos en la célula vegetal?', options: ['Five: wall, chloroplast, membrane, large vacuole, nucleus', 'Three', 'One'], oes: ['Cinco: pared, cloroplasto, membrana, vacuola grande, núcleo', 'Tres', 'Una'], a: 0 },
    { type: 'reto', world: 'cellparts', q: 'How many parts do we label in the animal cell?', es: '¿Cuántas partes ponemos en la célula animal?', options: ['Three: membrane, nucleus, small vacuole', 'Five', 'Seven'], oes: ['Tres: membrana, núcleo, vacuola pequeña', 'Cinco', 'Siete'], a: 0 },
    { type: 'reto', world: 'cellparts', q: 'What do a plant cell and an animal cell have in common?', es: '¿Qué tienen en común una célula vegetal y una animal?', options: ['Nucleus and cell membrane', 'Cell wall', 'Chloroplasts'], oes: ['núcleo y membrana celular', 'pared celular', 'cloroplastos'], a: 0 },
    // The five kingdoms
    { type: 'choice', world: 'kingdoms', q: 'How many kingdoms are there?', es: '¿Cuántos reinos hay?', options: ['Three', 'Four', 'Five', 'Six'], oes: ['tres', 'cuatro', 'cinco', 'seis'], a: 2 },
    { type: 'choice', world: 'kingdoms', q: 'Which kingdom makes its own food?', es: '¿Qué reino fabrica su propio alimento?', options: ['Plants', 'Animals', 'Fungi', 'Monera'], oes: ['plantas', 'animales', 'hongos', 'moneras'], a: 0 },
    { type: 'choice', world: 'kingdoms', q: 'Which kingdom lays eggs or gives birth?', es: '¿Qué reino pone huevos o da a luz a crías?', options: ['Plants', 'Animals', 'Fungi', 'Protists'], oes: ['plantas', 'animales', 'hongos', 'protistas'], a: 1 },
    { type: 'choice', world: 'kingdoms', q: 'Which kingdom cannot move and gets nutrients from dead plants and animals?', es: '¿Qué reino no puede moverse y obtiene nutrientes de plantas y animales muertos?', options: ['Plants', 'Animals', 'Fungi', 'Protists'], oes: ['plantas', 'animales', 'hongos', 'protistas'], a: 2 },
    { type: 'choice', world: 'kingdoms', q: 'Bacteria belong to the kingdom…', es: 'Las bacterias pertenecen al reino…', options: ['Monera', 'Fungi', 'Plants', 'Animals'], oes: ['moneras', 'hongos', 'plantas', 'animales'], a: 0 },
    { type: 'choice', world: 'kingdoms', q: 'Amoebas and algae belong to the kingdom…', es: 'Las amebas y las algas pertenecen al reino…', options: ['Protists', 'Monera', 'Fungi', 'Animals'], oes: ['protistas', 'moneras', 'hongos', 'animales'], a: 0 },
    { type: 'choice', world: 'kingdoms', q: 'Mushrooms belong to the kingdom…', es: 'Las setas pertenecen al reino…', options: ['Plants', 'Fungi', 'Animals', 'Monera'], oes: ['plantas', 'hongos', 'animales', 'moneras'], a: 1, why: 'Mushrooms are fungi: they cannot move and get nutrients from dead plants and animals.', wes: 'Las setas son hongos: no se mueven y obtienen nutrientes de plantas y animales muertos.' },
    { type: 'choice', world: 'kingdoms', q: 'Which kingdom is unicellular?', es: '¿Qué reino es unicelular?', options: ['Monera', 'Plants', 'Animals'], oes: ['moneras', 'plantas', 'animales'], a: 0 },
    { type: 'choice', world: 'kingdoms', q: 'Most protists live…', es: 'La mayoría de los protistas viven…', options: ['in or near water', 'in the desert', 'on the moon'], oes: ['en el agua o cerca', 'en el desierto', 'en la luna'], a: 0 },
    { type: 'choice', world: 'kingdoms', q: 'Which kingdom feeds on other living things?', es: '¿Qué reino se alimenta de otros seres vivos?', options: ['Animals', 'Plants', 'Monera'], oes: ['animales', 'plantas', 'moneras'], a: 0 },
    { type: 'tf', world: 'kingdoms', s: 'There are five kingdoms.', es: 'Hay cinco reinos.', a: true },
    { type: 'tf', world: 'kingdoms', s: 'Plants feed on other living things.', es: 'Las plantas se alimentan de otros seres vivos.', a: false, why: 'Plants make their own food. Animals feed on other living things.', wes: 'Las plantas fabrican su propio alimento. Los animales se alimentan de otros seres vivos.' },
    { type: 'tf', world: 'kingdoms', s: 'Fungi can move.', es: 'Los hongos pueden moverse.', a: false, why: 'Fungi cannot move.', wes: 'Los hongos no pueden moverse.' },
    { type: 'tf', world: 'kingdoms', s: 'Monera are unicellular.', es: 'Las moneras son unicelulares.', a: true },
    { type: 'tf', world: 'kingdoms', s: 'A mushroom is a plant.', es: 'Una seta es una planta.', a: false, why: 'A mushroom is a fungus (kingdom fungi).', wes: 'Una seta es un hongo (reino de los hongos).' },
    { type: 'tf', world: 'kingdoms', s: 'Animals are multicellular.', es: 'Los animales son pluricelulares.', a: true },
    { type: 'tf', world: 'kingdoms', s: 'Protists are usually unicellular.', es: 'Los protistas son generalmente unicelulares.', a: true },
    { type: 'tf', world: 'kingdoms', s: 'Fungi can be multicellular or unicellular.', es: 'Los hongos pueden ser pluricelulares o unicelulares.', a: true },
    { type: 'reto', world: 'kingdoms', q: 'A living thing with many cells that makes its own food. Which kingdom?', es: 'Un ser vivo con muchas células que fabrica su propio alimento. ¿Qué reino?', options: ['Plants', 'Animals', 'Fungi'], oes: ['plantas', 'animales', 'hongos'], a: 0 },
    { type: 'reto', world: 'kingdoms', q: 'A living thing with one cell that lives in water. Which kingdom?', es: 'Un ser vivo con una sola célula que vive en el agua. ¿Qué reino?', options: ['Protists', 'Plants', 'Animals'], oes: ['protistas', 'plantas', 'animales'], a: 0, why: 'Protists are usually unicellular and most live in or near water.', wes: 'Los protistas son generalmente unicelulares y la mayoría viven en el agua o cerca.' },
    { type: 'reto', world: 'kingdoms', q: 'Chopper is a reindeer: he eats and was born from his mum. Which kingdom?', es: 'Chopper es un reno: come y nació de su mamá. ¿Qué reino?', options: ['Animals', 'Plants', 'Monera'], oes: ['animales', 'plantas', 'moneras'], a: 0 },
    { type: 'reto', world: 'kingdoms', q: 'A mushroom and a rabbit: what is the difference?', es: 'Una seta y un conejo: ¿en qué se diferencian?', options: ['The mushroom cannot move and the rabbit can', 'The mushroom makes its own food', 'The rabbit is unicellular'], oes: ['La seta no se mueve y el conejo sí', 'La seta fabrica su propio alimento', 'El conejo es unicelular'], a: 0 },
    { type: 'reto', world: 'kingdoms', q: 'Which two kingdoms feed on dead plants and animals?', es: '¿Qué dos reinos se alimentan de plantas y animales muertos?', options: ['Fungi and monera', 'Plants and animals', 'Animals and protists'], oes: ['hongos y moneras', 'plantas y animales', 'animales y protistas'], a: 0 },
    { type: 'reto', world: 'kingdoms', q: 'Something green that makes its own food but has only one cell and lives in water. Which kingdom?', es: 'Algo verde que fabrica su alimento pero tiene una sola célula y vive en el agua. ¿Qué reino?', options: ['Protists (algae)', 'Plants', 'Fungi'], oes: ['protistas (las algas)', 'plantas', 'hongos'], a: 0, why: 'Algae are protists: usually unicellular, in or near water.', wes: 'Las algas son protistas: generalmente unicelulares, en el agua o cerca.' },
    { type: 'reto', world: 'kingdoms', q: 'Which kingdom would Luffy\'s crew visit to find bacteria?', es: '¿A qué reino iría la tripulación de Luffy para encontrar bacterias?', options: ['Monera', 'Fungi', 'Plants'], oes: ['moneras', 'hongos', 'plantas'], a: 0 },
  ];

  // ---------- escenas para PONER NOMBRES (dibujadas en SVG en scenes.js; x,y en % del dibujo). Los nombres van en inglés con su castellano ----------
  const scenes = {
    animal_cell: { world: 'cellparts', svg: 'animal_cell', ratio: 4 / 3, title: 'The animal cell', rounds: [
      { title: 'Label the animal cell', es: 'Pon los nombres de la célula animal', labels: [{ id: 'membrane', text: 'cell membrane', es: 'membrana celular', x: 26, y: 24 }, { id: 'nucleus', text: 'nucleus', es: 'núcleo', x: 50, y: 52 }, { id: 'small_vacuole', text: 'small vacuole', es: 'vacuola pequeña', x: 76, y: 30 }] },
    ] },
    plant_cell: { world: 'cellparts', svg: 'plant_cell', ratio: 4 / 3, title: 'The plant cell', rounds: [
      { title: 'Label the plant cell', es: 'Pon los nombres de la célula vegetal', labels: [{ id: 'wall', text: 'cell wall', es: 'pared celular', x: 10, y: 50 }, { id: 'pmembrane', text: 'cell membrane', es: 'membrana celular', x: 20, y: 22 }, { id: 'chloroplast', text: 'chloroplast', es: 'cloroplasto', x: 76, y: 28 }, { id: 'large_vacuole', text: 'large vacuole', es: 'vacuola grande', x: 44, y: 56 }, { id: 'pnucleus', text: 'nucleus', es: 'núcleo', x: 73, y: 66 }] },
    ] },
    organisation: { world: 'cells', svg: 'organisation', ratio: 4 / 3, title: 'How cells are organised', rounds: [
      { title: 'The levels of organisation', es: 'Los niveles de organización', labels: [{ id: 'cell', text: 'cell', es: 'célula', x: 10, y: 30 }, { id: 'tissue', text: 'tissue', es: 'tejido', x: 30, y: 30 }, { id: 'organ', text: 'organ', es: 'órgano', x: 50, y: 30 }, { id: 'system', text: 'organ system', es: 'sistema de órganos', x: 70, y: 30 }, { id: 'organism', text: 'organism', es: 'organismo', x: 90, y: 30 }] },
      { title: 'The animal example', es: 'El ejemplo del animal', labels: [{ id: 'a_cell', text: 'cell', es: 'célula', x: 10, y: 30 }, { id: 'a_tissue', text: 'tissue', es: 'tejido', x: 30, y: 30 }, { id: 'heart', text: 'heart', es: 'corazón', x: 50, y: 30 }, { id: 'circulatory', text: 'circulatory system', es: 'sistema circulatorio', x: 70, y: 30 }, { id: 'animal', text: 'animal', es: 'animal', x: 90, y: 30 }] },
      { title: 'The plant example', es: 'El ejemplo de la planta', labels: [{ id: 'p_cell', text: 'cell', es: 'célula', x: 10, y: 74 }, { id: 'p_tissue', text: 'tissue', es: 'tejido', x: 30, y: 74 }, { id: 'leaf', text: 'leaf', es: 'hoja', x: 50, y: 74 }, { id: 'plant_system', text: 'plant organ system', es: 'sistema de órganos de la planta', x: 70, y: 74 }, { id: 'plant', text: 'plant', es: 'planta', x: 90, y: 74 }] },
    ] },
    living_tree: { world: 'living', svg: 'living_tree', ratio: 4 / 3, title: 'Living and non-living things', rounds: [
      { title: 'Name the four groups', es: 'Pon el nombre de los cuatro grupos', labels: [{ id: 'animals', text: 'animals', es: 'animales', x: 14, y: 46 }, { id: 'plants', text: 'plants', es: 'plantas', x: 38, y: 46 }, { id: 'natural', text: 'natural', es: 'naturales', x: 62, y: 46 }, { id: 'artificial', text: 'artificial', es: 'artificiales', x: 86, y: 46 }] },
      { title: 'Living or non-living?', es: '¿Vivos o inertes?', labels: [{ id: 'living', text: 'living things', es: 'seres vivos', x: 26, y: 15 }, { id: 'nonliving', text: 'non-living things', es: 'seres inertes', x: 74, y: 15 }] },
    ] },
    kingdoms: { world: 'kingdoms', svg: 'kingdoms', ratio: 4 / 3, title: 'The five kingdoms', rounds: [
      { title: 'Name the five kingdoms', es: 'Pon el nombre de los cinco reinos', labels: [{ id: 'k_plants', text: 'plants', es: 'plantas', x: 17, y: 20 }, { id: 'k_animals', text: 'animals', es: 'animales', x: 50, y: 20 }, { id: 'k_fungi', text: 'fungi', es: 'hongos', x: 83, y: 20 }, { id: 'k_monera', text: 'monera', es: 'moneras', x: 30, y: 70 }, { id: 'k_protists', text: 'protists', es: 'protistas', x: 70, y: 70 }] },
    ] },
    vital: { world: 'living', svg: 'vital', ratio: 4 / 3, title: 'The vital functions', rounds: [
      { title: 'Name the three vital functions', es: 'Pon el nombre de las tres funciones vitales', labels: [{ id: 'f_nutrition', text: 'nutrition', es: 'nutrición', x: 17, y: 20 }, { id: 'f_reproduction', text: 'reproduction', es: 'reproducción', x: 50, y: 20 }, { id: 'f_interaction', text: 'interaction', es: 'interacción', x: 83, y: 20 }] },
    ] },
  };

  // ---------- vocabulario: inglés → castellano (para las fichas de las listas y lo que no lleve traducción propia) ----------
  const VOCAB = {
    'flamingo': 'flamenco', 'fox': 'zorro', 'seal': 'foca', 'tree': 'árbol', 'flower': 'flor', 'sun': 'sol', 'volcano': 'volcán', 'bicycle': 'bicicleta', 'balloon': 'globo', 'wave': 'ola', 'shoes': 'zapatillas', 'sea': 'mar', 'rock': 'roca', 'car': 'coche',
    'nutrition': 'nutrición', 'reproduction': 'reproducción', 'interaction': 'interacción', 'flying': 'volar', 'sleeping': 'dormir', 'running': 'correr', 'talking': 'hablar',
    'bacteria': 'bacterias', 'algae': 'algas', 'amoeba': 'ameba', 'dog': 'perro', 'person': 'persona', 'rabbit': 'conejo', 'plant': 'planta', 'animal': 'animal', 'bird': 'pájaro', 'mushroom': 'seta', 'sunflower': 'girasol',
    'cell': 'célula', 'tissue': 'tejido', 'organ': 'órgano', 'organ system': 'sistema de órganos', 'organism': 'organismo', 'microscope': 'microscopio', 'kingdom': 'reino', 'food': 'alimento',
    'cell wall': 'pared celular', 'chloroplast': 'cloroplasto', 'cell membrane': 'membrana celular', 'large vacuole': 'vacuola grande', 'nucleus': 'núcleo', 'small vacuole': 'vacuola pequeña', 'heart': 'corazón', 'leaf': 'hoja', 'bone': 'hueso',
    'plants': 'plantas', 'animals': 'animales', 'fungi': 'hongos', 'monera': 'moneras', 'protists': 'protistas', 'insects': 'insectos', 'fish': 'peces', 'birds': 'pájaros', 'rocks': 'rocas',
    'living things': 'seres vivos', 'non-living things': 'seres inertes', 'natural': 'natural', 'artificial': 'artificial', 'unicellular': 'unicelular', 'multicellular': 'pluricelular', 'both': 'las dos', 'true': 'verdadero', 'false': 'falso',
  };

  // ---------- «¿Sabías que…?» en castellano (sorpresas de los sobres; todo cierto) ----------
  const facts = [
    { id: 'f1', world: 'living', text: 'Tu cuerpo está hecho de unos 37 billones de células. ¡Un 37 seguido de doce ceros!' },
    { id: 'f2', world: 'living', text: 'La ballena azul es el animal más grande que ha existido nunca: mide como tres autobuses seguidos.' },
    { id: 'f3', world: 'living', text: '¡Hay plantas que comen insectos! La venus atrapamoscas cierra sus hojas como una boca cuando se posa una mosca.' },
    { id: 'f4', world: 'cells', text: 'Un científico llamado Robert Hooke les puso el nombre a las células en 1665, porque le recordaban a las habitaciones pequeñas de los monjes, que se llamaban «celdas».' },
    { id: 'f5', world: 'cells', text: 'Las bacterias son tan pequeñas que en la punta de un lápiz cabrían millones.' },
    { id: 'f6', world: 'cells', text: 'Un huevo de avestruz es la célula más grande que puedes tener en la mano: la yema es una sola célula.' },
    { id: 'f7', world: 'cellparts', text: 'Los cloroplastos son verdes por la clorofila, que atrapa la luz del sol para que la planta fabrique su alimento.' },
    { id: 'f8', world: 'cellparts', text: 'Las plantas se mantienen de pie sin huesos gracias a la pared celular de cada una de sus células.' },
    { id: 'f9', world: 'cellparts', text: '¡Tus glóbulos rojos no tienen núcleo! Lo pierden para poder llevar más oxígeno.' },
    { id: 'f10', world: 'kingdoms', text: 'El ser vivo más grande de la Tierra es un hongo de Oregón, en Estados Unidos: se extiende bajo tierra por más de nueve kilómetros cuadrados.' },
    { id: 'f11', world: 'kingdoms', text: '¡Las setas son parientes más cercanas de los animales que de las plantas!' },
    { id: 'f12', world: 'kingdoms', text: 'Una ameba se mueve cambiando de forma, y come envolviendo la comida con su cuerpo.' },
  ];

  // los chistes son los de Ciencias Sociales, en castellano (CS.jokes, con sus voces ya grabadas); quién habla con qué voz:
  const VOICE_OF = { Deku: 'boy', Hinata: 'boy', Luffy: 'boy', Nezuko: 'girl' };

  // ---------- frases con voz: saludos de los personajes en castellano; el resto de instrucciones son las de Ciencias (l_*) ----------
  const lines = {
    w_living: '¡Hola, María! Soy Deku. Los héroes comen, crecen y cuidan el mundo que los rodea. ¡Vamos a descubrir los seres vivos, en inglés!',
    w_cells: '¡Hola, María! Soy Hinata. Un jugador es como una célula, y el equipo entero es el organismo. ¡Vamos!',
    w_cellparts: '¡Hola, María! Soy Nezuko. Mi bambú es duro como la pared de una célula vegetal. ¡Vamos a mirar dentro de las células!',
    w_kingdoms: '¡Hola, María! Soy Luffy. ¡Cinco reinos por explorar, y quiero ser el rey de todos!',
    ns_intro: '¡Hola, María! Bienvenida a Natural Science. Cuatro fichas en inglés, con su castellano al lado para que lo entiendas todo. ¡Vamos!',
    prize: '¡Premio especial! Diez minutos de YouTube. ¡Te lo has ganado!',
  };

  const byWorld = (arr, w) => arr.filter(x => x.world === w);
  // nombre estable (hash corto) para el clip de voz de cada pregunta: la misma función en el generador de audio
  const hash = t => { let h = 5381; const n = String(t); for (let i = 0; i < n.length; i++) h = ((h * 33) ^ n.charCodeAt(i)) >>> 0; return h.toString(36); };
  // castellano de una palabra o frase corta del vocabulario ('' si no está)
  const es = t => { const k = String(t || '').toLowerCase().trim(); return VOCAB[k] || VOCAB[k.replace(/^(a|an|the) /, '')] || ''; };
  // concepto → punto de una escena (para enseñarlo señalándolo y para «toca el…»)
  const SPOT = { cell: ['organisation', 'cell'], organised: ['organisation', 'organism'], animal_example: ['organisation', 'heart'], plant_example: ['organisation', 'leaf'], living_groups: ['living_tree', 'living'], nonliving_groups: ['living_tree', 'nonliving'], natural_things: ['living_tree', 'natural'], artificial_things: ['living_tree', 'artificial'], nutrition: ['vital', 'f_nutrition'], reproduction: ['vital', 'f_reproduction'], interaction: ['vital', 'f_interaction'], five_kingdoms: ['kingdoms', 'k_plants'], plants_k: ['kingdoms', 'k_plants'], animals_k: ['kingdoms', 'k_animals'], fungi_k: ['kingdoms', 'k_fungi'], monera_k: ['kingdoms', 'k_monera'], protists_k: ['kingdoms', 'k_protists'], plant_cell_parts: ['plant_cell', 'wall'], animal_cell_parts: ['animal_cell', 'nucleus'], cell_difference: ['plant_cell', 'chloroplast'] };
  // dibujo que se enseña con un concepto sin punto propio (una escena de su mundo)
  const TEACH_SCENE = { living_things: 'living_tree', vital_functions: 'vital', cell_types: 'plant_cell', microscope: 'organisation', unicellular: 'kingdoms', multicellular: 'organisation' };
  return { hash, es, VOCAB, SPOT, TEACH_SCENE, VOICE_OF, worlds, WORLD_ORDER, concepts, lists, sorts, questions, scenes, facts, lines, byWorld, concept: id => concepts.find(c => c.id === id) };
})();
